# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
bioc_required: true
bioc_use_devel: true

before_install:
 - wget 'http://downloads.sourceforge.net/project/sbml/libsbml/5.11.4/stable/Linux/64-bit/libSBML-5.11.4-Linux-x64.deb?r=&ts=1435974035' -O libSBML.deb
 - sudo dpkg -i libSBML.deb

# System dependencies for HTTP calling
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 
env:
 global:
   - CRAN: http://cran.rstudio.com

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:
 - igraph/igraph

notifications:
  email:
    on_success: change
    on_failure: change
